PYTHONPATH shenanigan
Running:

  git clean -fxd && make

Will produce the following error:

  extracting messages from about.html.j2 (encoding="utf-8", lstrip_blocks="True", trim_blocks="True")
  Traceback (most recent call last):
    File "/gnu/store/2dv8956ggc15s3yidadkw38v6ksi36k5-python-babel-2.6.0/bin/.pybabel-real", line 11, in <module>
     load_entry_point('Babel==2.6.0', 'console_scripts', 'pybabel')()
    File "/gnu/store/2dv8956ggc15s3yidadkw38v6ksi36k5-python-babel-2.6.0/lib/python3.7/site-packages/babel/messages/frontend.py", line 911, in main
     return CommandLineInterface().run(sys.argv)
    File "/gnu/store/2dv8956ggc15s3yidadkw38v6ksi36k5-python-babel-2.6.0/lib/python3.7/site-packages/babel/messages/frontend.py", line 835, in run
     return cmdinst.run()
    File "/gnu/store/2dv8956ggc15s3yidadkw38v6ksi36k5-python-babel-2.6.0/lib/python3.7/site-packages/babel/messages/frontend.py", line 470, in run
     for filename, lineno, message, comments, context in extracted:
    File "/gnu/store/2dv8956ggc15s3yidadkw38v6ksi36k5-python-babel-2.6.0/lib/python3.7/site-packages/babel/messages/extract.py", line 157, in extract_from_dir
     dirpath=absname,
    File "/gnu/store/2dv8956ggc15s3yidadkw38v6ksi36k5-python-babel-2.6.0/lib/python3.7/site-packages/babel/messages/extract.py", line 212, in check_and_call_extract_file
     strip_comment_tags=strip_comment_tags
    File "/gnu/store/2dv8956ggc15s3yidadkw38v6ksi36k5-python-babel-2.6.0/lib/python3.7/site-packages/babel/messages/extract.py", line 241, in extract_from_file
     strip_comment_tags))
    File "/gnu/store/2dv8956ggc15s3yidadkw38v6ksi36k5-python-babel-2.6.0/lib/python3.7/site-packages/babel/messages/extract.py", line 294, in extract
     func = getattr(__import__(module, {}, {}, [attrname]), attrname)
  ModuleNotFoundError: No module named 'i18nfix'

So we add current working directory aka. CWD in the pythonpath. But
since guix also has changed PYTHONPATH env variable we need to suffix
it. In bash that would have been simply:

export PYTHONPATH=$(pwd):$PYTHONPATH